reviews:
    auto: true
    profile: assertive
    tone: professional
    high_level_summary: true

    branches:
        include:
            - main

    instructions: |
        Act as a senior software engineer.
        Prefer unknown over any.
        Flag security vulnerabilities and hotspots.
        Highlight missing or insufficient tests.
        Point out architectural issues and code smells.
